### PR TITLE
Add a note documenting VLBI extensions to MSv2

### PR DESCRIPTION
**Pull request by kettenis**

### CODE REVIEW

**Comment by kettenis** [comment]
Initial stab at documenting VLBI extension tables currently supported by casacore (and used by CASA).  As requested by @tammojan and @dpetry

**Comment by kettenis** [comment]
Hi @tammojan I updated the note with comments from Des Small.  Please review.

**Review by tammojan — APPROVED** [review]
Looks good to me (modulo a typo `oreintation`).

**Comment by kettenis** [comment]
Fixed the typo.

**Review by tammojan — APPROVED** [review]

**Comment by kettenis** [comment]
@tammojan I don't think I can merge this myself. So can you do it?

**Pull request merged**
